namespace FocusKey.Foundation.Sessions;

/// <summary>
/// Stable identity of a focus session. Generated by the application before the row exists, so a
/// session can be logged and referenced independently of any storage detail. SQLite row ids are
/// never used as application identity.
/// </summary>
public readonly record struct SessionId
{
    /// <summary>Canonical persisted text form, for example <c>c1a0f9d6-...</c> (36 characters).</summary>
    public const int TextLength = 36;

    public SessionId(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException("A session id cannot be the empty GUID.", nameof(value));
        }

        Value = value;
    }

    public Guid Value { get; }

    /// <summary>True for <c>default(SessionId)</c>, which bypasses the constructor.</summary>
    public bool IsEmpty => Value == Guid.Empty;

    public static SessionId New() => new(Guid.NewGuid());

    /// <exception cref="FormatException">The text is not a canonical non-empty GUID.</exception>
    public static SessionId Parse(string? text) =>
        TryParse(text, out SessionId id)
            ? id
            : throw new FormatException($"'{text}' is not a valid session id.");

    public static bool TryParse(string? text, out SessionId id)
    {
        if (text is not null
            && Guid.TryParseExact(text, "D", out Guid value)
            && value != Guid.Empty)
        {
            id = new SessionId(value);
            return true;
        }

        id = default;
        return false;
    }

    /// <summary>The exact text written to storage.</summary>
    public string ToText() => Value.ToString("D");

    public override string ToString() => ToText();
}
